name: Trigger Shared Workflow

on:
  workflow_dispatch:
     inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: Dev
        type: choice
        options:
          - DEV
          - PROD

jobs:
  call-shared:
    uses: Pranjal-1515/Test-Shared/.github/workflows/02.Shared.yml@main
    with:
      env_name: ${{ github.event.inputs.environment }}
